erDiagram

    PATIENT       ||--o{ NOTE          : "possède (lien logique cross-DB)"
    PATIENT       }o--o| CODE_POSTAL   : "domicilié à"

    PATIENT {
        bigint       id              PK "auto-incrément"
        varchar(50)  prenom            "NOT NULL"
        varchar(50)  nom               "NOT NULL"
        date         date_naissance    "NOT NULL"
        char(1)      genre             "NOT NULL — M ou F"
        varchar(20)  telephone         "nullable"
        varchar(100) adresse_ligne     "nullable"
        varchar(10)  code_postal       FK "nullable, ref CODE_POSTAL"
    }

    CODE_POSTAL {
        varchar(10) code_postal       PK "ex. 75001"
        varchar(50) ville              "NOT NULL — déduite du CP"
    }

    NOTE {
        ObjectId  _id                 PK "id Mongo"
        bigint    patient_id            "ref PATIENT.id (SQL) — index"
        varchar   praticien             "auteur de la note"
        datetime  date_note             "horodatage observation"
        text      contenu               "texte libre, peu structuré"
        string[]  termes_detectes       "cache des déclencheurs (optionnel)"
    }
