erDiagram

    PATIENT       ||--o{ NOTE          : "possède (lien logique cross-DB)"

    PATIENT {
        bigint       id              PK "auto-incrément"
        varchar(100)  prenom            "NOT NULL"
        varchar(100)  nom               "NOT NULL"
        date         date_naissance    "NOT NULL"
        char(1)      genre             "NOT NULL — M ou F"
        varchar(20)  telephone         "nullable"
        varchar(255) adresse           "nullable"
    }

    NOTE {
        ObjectId  _id                 PK "id Mongo"
        bigint    patient_id            "ref PATIENT.id (SQL) — index"
        varchar   praticien             "auteur de la note"
        datetime  date_note             "horodatage observation"
        text      contenu               "texte libre, peu structuré"
        string[]  termes_detectes       "cache des déclencheurs (optionnel)"
    }
